---
title: "K-Means"
author: "Henry Siegler"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(tidyverse)
library(gganimate)
```

```{r}
k_means <- function(dat, k, pca = FALSE) {

    if(pca == TRUE){
        dat <- princomp(dat)
        dat <- dat$scores %>%
            as.data.frame() %>%
            select(Comp.1, Comp.2)
    }
    
    #randomly select the indices of k rows to use as starting
    #centers of the k clusters
    rand <- sample(1:nrow(dat), k)

    #dataframe with k observations that were randomly selected
    clusters <- dat[rand,]

    cluster_vec <- c()
    last_vec <- c(0)
    d_mins <- c()
    iter <- 0
    stop <- 0

    while (stop == 0) {

        iter <- iter + 1

        for (i in 1:nrow(dat)) {

            dist <- dat[i,] %>%
                rbind(clusters) %>%
                dist()

            i_cluster <- dist[1:k] %>%
                which.min()

            cluster_vec[i] <- i_cluster

        }

        if (all(cluster_vec == last_vec)) {
            stop <-  1
        }

        last_vec <- cluster_vec

        clusters <- dat %>%
            cbind(cluster_vec) %>%
            group_by(cluster_vec) %>%
            summarize_all(mean)

        clusters <- clusters[, -1]

    }

    list <- list('Clustering vector' = cluster_vec)
    return(list)
}
```


